cache:
  paths:
  - .gradle/

services:
  - docker:dind

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
- prepareci
- build

ciimage_job:
  image: docker:stable
  stage: prepareci
  script:
  - docker pull registry.gitlab.com/dajoni/spring-playground/gradle-ci:latest || true
  - docker build --cache-from=registry.gitlab.com/dajoni/spring-playground/gradle-ci:latest -t registry.gitlab.com/dajoni/spring-playground/gradle-ci ci-image
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/dajoni/spring-playground/gradle-ci:latest

build_job:
  image: registry.gitlab.com/dajoni/spring-playground/gradle-ci:latest
  stage: build
  script:
  - gradle --no-daemon build docker dockerPush -info