
cache:
  paths:
  - .gradle/

before_script:

stages:
- prepareci
- build
- docker

ciimage_job:
  image: docker:latest
  services:
  - docker:dind
  stage: prepareci
  script:
  - docker build -t registry.gitlab.com/dajoni/spring-playground/gradle-ci ci-image
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/dajoni/spring-playground/gradle-ci

build_job:
  image: registry.gitlab.com/dajoni/spring-playground/gradle-ci
  stage: build
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - gradle --no-daemon build -info

docker_job:
  stage: registry.gitlab.com/dajoni/spring-playground/gradle-ci
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - gradle --no-daemon docker -info
