version: '2'

services:  
  producer:
    image: registry.gitlab.com/dajoni/spring-playground/event-producer:latest
    container_name: producer
    restart: always
    depends_on:
      - kafka
      - schemaregistry
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "5"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "5"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    stop_grace_period: 2m
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
    ports:
      - "9092:9092"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "5"

  schemaregistry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schemaregistry
    restart: always
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "5"