#server:
#  undertow:
#    accesslog:
#      enabled: true
#      dir: ${PLAYGROUND_DATA_DIR:./}logs

service:
  playground:
    some-url: https://myuri/
    names:
      - foo
      - bar
    application-users:
      - username: monitor
        password: monitor_me
        roles: MONITOR
      - username: serviceadmin
        password: admin123
        roles: ADMIN



