spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      client-id: event-producer
      batch-size: 16777216 # 16 megs
      properties:
        schema.registry.url: http://schemaregistry:8081

